# Generated by Django 2.1.1 on 2018-09-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_status_geral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe_trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Equipe de Trabalho')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição da Equipe de Trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Tipo da Atividade de Trabalho')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Tipo da Atividade de Trabalho')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição do Tipo da Atividade de Trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho_campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Tipo da Atividade de Trabalho')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição do Tipo da Atividade de Trabalho')),
                ('at_equipe_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Equipe_trabalho', verbose_name='Equipe de Trabalho da Atividade')),
                ('at_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Municipio', verbose_name='Municipio da Atividade')),
                ('at_tipo_atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Tipo_atividade', verbose_name='Tipo da Atividade de Trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_gestora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Unidade Gestora')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição da Unidade Gestora')),
                ('ug_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Municipio', verbose_name='Municipio da Unidade Gestora')),
            ],
        ),
        migrations.AddField(
            model_name='trabalho_campo',
            name='at_unidade_gestora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Unidade_gestora', verbose_name='Unidade Gestora da Atividade'),
        ),
        migrations.AddField(
            model_name='trabalho_campo',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
