# Generated by Django 2.1.1 on 2018-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0002_trabalho_campo_at_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atividade',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria da Atividade de Trabalho'),
        ),
    ]
