# Generated by Django 2.1.1 on 2018-09-18 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0006_auto_20180914_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atividade', '0004_trabalho_campo_dt_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('num_protocolo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero do protocolo da ocorrência')),
                ('dt_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('nome_solicitante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Solicitante da ocorrência')),
                ('tel_solicitante', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone do Solicitante')),
                ('email_solicitante', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-mail do Solicitante')),
                ('questionamento', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Questionamento da ocorrência')),
                ('dt_solucao_ocorrencia', models.DateTimeField(blank=True, null=True)),
                ('beneficiario_participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participante.Participante', verbose_name='Beneficiário da ocorrencia')),
                ('equipe_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Equipe_trabalho', verbose_name='Equipe responsável pela ocorrência')),
                ('user_atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Municipio da ocorrência')),
            ],
        ),
    ]
