# Generated by Django 2.1.1 on 2018-09-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_status_geral'),
        ('atividade', '0005_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Status_Geral'),
        ),
    ]
