# Generated by Django 2.1.1 on 2018-09-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0006_ocorrencia_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa_correncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo da solução')),
                ('solucao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Solução adotada')),
                ('dt_solucao', models.DateTimeField(blank=True, null=True)),
                ('equipe_responsavel_solucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Equipe_trabalho', verbose_name='Equipe responsável pela solução da ocorrência')),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atividade.Ocorrencia')),
            ],
        ),
    ]
