# Generated by Django 2.1.1 on 2018-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Geral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('chave', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', models.CharField(blank=True, max_length=200, null=True)),
                ('next', models.IntegerField(blank=True, null=True)),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
