# Generated by Django 2.1.1 on 2018-09-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0012_participante_card_id'),
        ('escola', '0002_auto_20180920_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='aluno_participa_turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participante.Participante')),
            ],
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Matutino e Vespertino', 'Matutino e Vespertino'), ('Matutino e Noturno', 'Matutino e Noturno'), ('Vespertino e Noturno', 'Vespertino e Noturno'), ('Matutino, Vespertino e Noturno', 'Matutino, Vespertino e Noturno')], default='Matutino', max_length=20, null=True, verbose_name='Turno escolar'),
        ),
        migrations.AddField(
            model_name='aluno_participa_turma',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Turma'),
        ),
    ]
