# Generated by Django 2.1.1 on 2018-09-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0012_participante_card_id'),
        ('escola', '0003_auto_20180920_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula_frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dia_semana', models.CharField(blank=True, max_length=500)),
                ('data_aula', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participante.Participante')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Turma')),
            ],
        ),
    ]
