# Generated by Django 2.1.1 on 2018-09-13 12:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.FileField(blank=True, default='usuario/perfil_default.png', max_length=1000, null=True, upload_to=dashboard.models.generate_name_file, verbose_name='BUSCAR ARQUIVO NO COMPUTADOR')),
            ],
        ),
    ]
