# Generated by Django 2.1.1 on 2018-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='foto_perfil',
            field=models.FileField(blank=True, default='usuario/perfil_default.png', max_length=1000, null=True, upload_to='teste', verbose_name='BUSCAR ARQUIVO NO COMPUTADOR'),
        ),
    ]
