# Generated by Django 2.1.1 on 2018-09-14 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_status_geral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True)),
                ('nis_pis', models.CharField(blank=True, max_length=15, verbose_name='Número do NIS')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='Número do CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='Número do RG')),
                ('rg_orgao_exp', models.CharField(blank=True, max_length=20, verbose_name='Órgão expedidor do RG')),
                ('rg_uf', models.CharField(blank=True, max_length=2, verbose_name='UF do RG')),
                ('nome_pai', models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe')),
                ('dt_nascimento', models.DateTimeField(blank=True, verbose_name='Data de nascimento do participante')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('ND', 'Não declarar')], max_length=20, verbose_name='Sexo do participante')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=50, verbose_name='Titulo de eleitor do participante')),
                ('ctps', models.CharField(max_length=100, null=True, verbose_name='Carteira de trabalho Nº')),
                ('ctps_serie', models.CharField(max_length=100, null=True, verbose_name='Série da carteira de trabalho')),
                ('ctps_uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, verbose_name='UF da carteira de trabalho')),
                ('cnpj_ultimo_empregador', models.CharField(blank=True, max_length=25, verbose_name='Número do documento do último empregador')),
                ('nome_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da empresa (Razão Social)')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função realizada pelo participante')),
                ('dt_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data inicial de contrato de trabalho')),
                ('dt_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data final de contrato de trabalho')),
                ('qtd_filhos_0_m_6_m', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 0 a 6 meses')),
                ('qtd_filhos_7_m_3_a', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 7 meses a 3 anos')),
                ('qtd_filhos_4_a_7_a', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 4 a 7 anos')),
                ('qtd_filhos_8_a_12_a', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 8 a 12 anos')),
                ('qtd_filhos_13_a_17_a', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 13 a 17 anos')),
                ('qtd_filhos_18_a_29_a', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 18 a 29 anos')),
                ('gestante_familia', models.BooleanField(blank=True, verbose_name='Existe gestante na familia')),
                ('alfabetizado', models.BooleanField(blank=True, verbose_name='participante é alfabetizado')),
                ('estudando', models.BooleanField(blank=True, verbose_name='Está estudando')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número do endereco do participante')),
                ('complemento', models.CharField(blank=True, max_length=150, verbose_name='Complemento do endereco do participante')),
                ('cep', models.CharField(blank=True, max_length=50, verbose_name='cep do participante')),
                ('fone', models.CharField(blank=True, max_length=50, verbose_name='Número de telefone do participante')),
                ('celular', models.CharField(blank=True, max_length=50, verbose_name='Número de celular do participante')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Renda mensal do participante')),
                ('qtd_pessoas_casa', models.IntegerField(blank=True, verbose_name='Quantidade de pessoas que moram na casa')),
                ('qtd_pessoas_contribuem_renda', models.IntegerField(blank=True, verbose_name='Quantidade de pessoas que contribuem com a renda')),
                ('verificacao_nis', models.BooleanField(null=True, verbose_name='Apresentou copia do ')),
                ('verificacao_contrato_trabalho', models.BooleanField(null=True, verbose_name='Apresentou copia do contrato de trabalho')),
                ('verificacao_ctps', models.BooleanField(null=True, verbose_name='Apresentou copia do ctps')),
                ('verificacao_cpf', models.BooleanField(null=True, verbose_name='Apresentou copia do cpf')),
                ('verificacao_rg', models.BooleanField(null=True, verbose_name='Apresentou copia do rg')),
                ('verificacao_endereco', models.BooleanField(null=True, verbose_name='Apresentou copia do endereco')),
                ('estado_civil', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.EstadoCivil', verbose_name='Estado civil do participante')),
                ('grau_escolaridade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.GrauEscolaridade', verbose_name='Grau de escolaridade do participante')),
                ('municipio_naturalidade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Municipio', verbose_name='Naturalidade do participante')),
                ('municipio_participante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipio_participante', to='core.Municipio', verbose_name='Municipio do participante')),
                ('portador_deficiencia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.Deficiencia', verbose_name='Portador de deficiencia')),
                ('raca', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.Raca', verbose_name='Raça do participante')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Status_Geral', verbose_name='Status do participante')),
                ('tipo_documento_empregador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.TipoDocumentoEmpregador', verbose_name='Tipo de documento do empregador')),
                ('turno_atividade_escolar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='participante.TurnoEscolar', verbose_name='Turno em que esta estudando atualmente')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
