# Generated by Django 2.1.1 on 2018-09-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Completo'),
        ),
    ]
