# Generated by Django 2.1.1 on 2018-09-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0004_auto_20180913_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='dt_nascimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de nascimento do participante'),
        ),
    ]
