# Generated by Django 2.1.1 on 2018-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0006_auto_20180914_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='verificacao_dados_participante',
            field=models.BooleanField(default=False, verbose_name='Alguma pendência nos dados do participante'),
        ),
        migrations.AddField(
            model_name='participante',
            name='verificacao_documentacao',
            field=models.BooleanField(default=False, verbose_name='Alguma pendência na entrega da documentacao'),
        ),
        migrations.AddField(
            model_name='participante',
            name='verificacao_representante_legal',
            field=models.BooleanField(default=False, verbose_name='Alguma pendência nos dados do representante legal'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='alfabetizado',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='participante é alfabetizado'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='estudando',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Está estudando'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='gestante_familia',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], verbose_name='Existe gestante na familia'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='rg_uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, null=True, verbose_name='UF do RG'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_contrato_trabalho',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do contrato de trabalho'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_cpf',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do cpf'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_ctps',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do ctps'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_endereco',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do endereco'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_nis',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do NIS'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='verificacao_rg',
            field=models.BooleanField(default=False, verbose_name='Apresentou copia do rg'),
        ),
    ]
