# Generated by Django 2.1.1 on 2018-09-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0007_auto_20180917_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='alfabetizado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], null=True, verbose_name='participante é alfabetizado'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='estudando',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], null=True, verbose_name='Está estudando'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='gestante_familia',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], null=True, verbose_name='Existe gestante na familia'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='rg_uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, null=True, verbose_name='UF do RG'),
        ),
    ]
