# Generated by Django 2.1.1 on 2018-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0008_auto_20180917_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='possui_representante_legal',
            field=models.BooleanField(default=True, verbose_name='Possui representante legal'),
        ),
        migrations.AddField(
            model_name='participante',
            name='representante_legal_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF do representante legal'),
        ),
        migrations.AddField(
            model_name='participante',
            name='representante_legal_dt_nascimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de nascimento do representante legal'),
        ),
        migrations.AddField(
            model_name='participante',
            name='representante_legal_nis_pis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIS/PIS do representante legal'),
        ),
        migrations.AddField(
            model_name='participante',
            name='representante_legal_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do representante legal'),
        ),
    ]
