# Generated by Django 2.1.1 on 2018-09-19 01:33

from django.db import migrations, models
import django.db.models.deletion
import participante.utils


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0009_auto_20180918_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, max_length=1000, null=True, upload_to=participante.utils.update_filename, verbose_name='BUSCAR ARQUIVO NO COMPUTADOR')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCopiaDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=500, verbose_name='Tipo da cópia do documento')),
                ('nome_bd', models.CharField(blank=True, max_length=500, verbose_name='Nome do documento para utilizar no sistema')),
            ],
        ),
        migrations.AlterField(
            model_name='participante',
            name='possui_representante_legal',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], default=True, verbose_name='Possui representante legal'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='possui_representante_legal',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], default=True,
                                      verbose_name='Possui representante legal'),
        ),
    ]
