# Generated by Django 2.1.1 on 2018-09-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0010_auto_20180918_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='alfabetizado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], default=1, null=True, verbose_name='participante é alfabetizado'),
        ),
    ]
