# Generated by Django 2.1.1 on 2018-09-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0011_auto_20180918_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
