# Generated by Django 2.1.1 on 2018-09-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0012_participante_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosparticipante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participante.Participante'),
        ),
    ]
