# Generated by Django 2.1.1 on 2018-09-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0013_documentosparticipante_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosparticipante',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participante.TipoCopiaDocumento', verbose_name='Tipo do documento'),
        ),
    ]
